#!/bin/bash

AUTHORIZATION_PLUGIN_CONFIG="<plugins>\n<jaasCertificateAuthenticationPlugin configuration=\"CertLogin\" \/>\n<authorizationPlugin>\n<map>\n<authorizationMap>\n<authorizationEntries>"
FOUND_CONFIG="false"
#topics
if [ -v ACTIVE_MQ_AUTHORIZATION_TOPIC_NAMES ]; then
   echo "Topics authorization found ..."
   FOUND_CONFIG="true"
   IFS=', ' read -r -a ACTIVE_MQ_AUTHORIZATION_TOPIC_NAMES_ARRAY <<< "${ACTIVE_MQ_AUTHORIZATION_TOPIC_NAMES}"
   for TOPIC_NAME in "${ACTIVE_MQ_AUTHORIZATION_TOPIC_NAMES_ARRAY[@]}"
   do
      TOPIC_CONFIG_LINES="<authorizationEntry topic=\\\"${TOPIC_NAME}\\\""
      echo "Checking '$TOPIC_NAME' configuration"
      TOPIC_NAME_VAR=${TOPIC_NAME//./_}
      READ_TOPIC_GROUP="ACTIVE_MQ_AUTHORIZATION_TOPIC_${TOPIC_VAR}_READ"
      if [ -v "$READ_TOPIC_GROUP" ]; then TOPIC_CONFIG_LINES="$TOPIC_CONFIG_LINES read=\\\"${!READ_TOPIC_GROUP}\\\" "; fi
      WRITE_TOPIC_GROUP="ACTIVE_MQ_AUTHORIZATION_TOPIC_${TOPIC_NAME_VAR}_WRITE"
      if [ -v "$WRITE_TOPIC_GROUP" ]; then TOPIC_CONFIG_LINES="$TOPIC_CONFIG_LINES write=\\\"${!WRITE_TOPIC_GROUP}\\\" "; fi
      ADMIN_TOPIC_GROUP="ACTIVE_MQ_AUTHORIZATION_TOPIC_${TOPIC_NAME_VAR}_ADMIN"
      if [ -v "$ADMIN_TOPIC_GROUP" ]; then TOPIC_CONFIG_LINES="$TOPIC_CONFIG_LINES admin=\\\"${!ADMIN_TOPIC_GROUP}\\\" "; fi
      TOPIC_CONFIG_LINES="$TOPIC_CONFIG_LINES \/>\n"
      AUTHORIZATION_PLUGIN_CONFIG="$AUTHORIZATION_PLUGIN_CONFIG\n$TOPIC_CONFIG_LINES"
   done
fi

#advisory topics
if [ -v ACTIVE_MQ_AUTHORIZATION_TOPIC_ADVISORY_READ ] || [ -v ACTIVE_MQ_AUTHORIZATION_TOPIC_ADVISORY_WRITE ] || [ -v ACTIVE_MQ_AUTHORIZATION_TOPIC_ADVISORY_ADMIN ]; then
   TOPIC_CONFIG_LINES="<authorizationEntry topic=\\\"ActiveMQ.Advisory.>\\\""
   if [ -v ACTIVE_MQ_AUTHORIZATION_TOPIC_ADVISORY_READ ]; then TOPIC_CONFIG_LINES="$TOPIC_CONFIG_LINES read=\\\"${ACTIVE_MQ_AUTHORIZATION_TOPIC_ADVISORY_READ}\\\""; fi
   if [ -v ACTIVE_MQ_AUTHORIZATION_TOPIC_ADVISORY_WRITE ]; then TOPIC_CONFIG_LINES="$TOPIC_CONFIG_LINES write=\\\"${ACTIVE_MQ_AUTHORIZATION_TOPIC_ADVISORY_WRITE}\\\""; fi
   if [ -v ACTIVE_MQ_AUTHORIZATION_TOPIC_ADVISORY_ADMIN ]; then TOPIC_CONFIG_LINES="$TOPIC_CONFIG_LINES admin=\\\"${ACTIVE_MQ_AUTHORIZATION_TOPIC_ADVISORY_ADMIN}\\\""; fi
   TOPIC_CONFIG_LINES="$TOPIC_CONFIG_LINES \/>\n"
   AUTHORIZATION_PLUGIN_CONFIG="$AUTHORIZATION_PLUGIN_CONFIG\n$TOPIC_CONFIG_LINES"
fi


#queues
if [ -v ACTIVE_MQ_AUTHORIZATION_QUEUE_NAMES ]; then
   echo "Queues authorization found ..."
   FOUND_CONFIG="true"
   IFS=', ' read -r -a ACTIVE_MQ_AUTHORIZATION_QUEUE_NAMES_ARRAY <<< "${ACTIVE_MQ_AUTHORIZATION_QUEUE_NAMES}"
   for QUEUE_NAME in "${ACTIVE_MQ_AUTHORIZATION_QUEUE_NAMES_ARRAY[@]}"
   do
      QUEUE_CONFIG_LINES="<authorizationEntry queue=\\\"${QUEUE_NAME}\\\""
      echo "Checking '$QUEUE_NAME' configuration"
      QUEUE_NAME_VAR=${QUEUE_NAME//./_}
      READ_QUEUE_GROUP="ACTIVE_MQ_AUTHORIZATION_QUEUE_${QUEUE_NAME_VAR}_READ"
      if [ -v "$READ_QUEUE_GROUP" ]; then QUEUE_CONFIG_LINES="$QUEUE_CONFIG_LINES read=\\\"${!READ_QUEUE_GROUP}\\\" "; fi
      WRITE_QUEUE_GROUP="ACTIVE_MQ_AUTHORIZATION_QUEUE_${QUEUE_NAME_VAR}_WRITE"
      if [ -v "$WRITE_QUEUE_GROUP" ]; then QUEUE_CONFIG_LINES="$QUEUE_CONFIG_LINES write=\\\"${!WRITE_QUEUE_GROUP}\\\" "; fi
      ADMIN_QUEUE_GROUP="ACTIVE_MQ_AUTHORIZATION_QUEUE_${QUEUE_NAME_VAR}_ADMIN"
      if [ -v "$ADMIN_QUEUE_GROUP" ]; then QUEUE_CONFIG_LINES="$QUEUE_CONFIG_LINES admin=\\\"${!ADMIN_QUEUE_GROUP}\\\" "; fi
      QUEUE_CONFIG_LINES="$QUEUE_CONFIG_LINES \/>\n"
      AUTHORIZATION_PLUGIN_CONFIG="$AUTHORIZATION_PLUGIN_CONFIG\n$QUEUE_CONFIG_LINES"
   done
fi
AUTHORIZATION_PLUGIN_CONFIG="$AUTHORIZATION_PLUGIN_CONFIG\n<\/authorizationEntries>"

#temp queues
if [ -v ACTIVE_MQ_AUTHORIZATION_TEMP_QUEUES_READ ] || [ -v ACTIVE_MQ_AUTHORIZATION_TEMP_QUEUES_WRITE ] || [ -v ACTIVE_MQ_AUTHORIZATION_TEMP_QUEUES_ADMIN ]; then
   echo "Temp queues authorization found ..."
   FOUND_CONFIG="true"
   TEMP_QUEUE_CONFIG_LINES="<tempDestinationAuthorizationEntry><tempDestinationAuthorizationEntry"
   if [ -v ACTIVE_MQ_AUTHORIZATION_TEMP_QUEUES_READ ]; then TEMP_QUEUE_CONFIG_LINES="$TEMP_QUEUE_CONFIG_LINES read=\\\"${ACTIVE_MQ_AUTHORIZATION_TEMP_QUEUES_READ}\\\""; fi
   if [ -v ACTIVE_MQ_AUTHORIZATION_TEMP_QUEUES_WRITE ]; then TEMP_QUEUE_CONFIG_LINES="$TEMP_QUEUE_CONFIG_LINES write=\\\"${ACTIVE_MQ_AUTHORIZATION_TEMP_QUEUES_WRITE}\\\""; fi
   if [ -v ACTIVE_MQ_AUTHORIZATION_TEMP_QUEUES_ADMIN ]; then TEMP_QUEUE_CONFIG_LINES="$TEMP_QUEUE_CONFIG_LINES admin=\\\"${ACTIVE_MQ_AUTHORIZATION_TEMP_QUEUES_ADMIN}\\\""; fi
   TEMP_QUEUE_CONFIG_LINES="$TEMP_QUEUE_CONFIG_LINES \/><\/tempDestinationAuthorizationEntry>\n"
   AUTHORIZATION_PLUGIN_CONFIG="$AUTHORIZATION_PLUGIN_CONFIG\n$TEMP_QUEUE_CONFIG_LINES"
fi

AUTHORIZATION_PLUGIN_CONFIG="$AUTHORIZATION_PLUGIN_CONFIG\n<\/authorizationMap>\n<\/map>\n<\/authorizationPlugin>\n<\/plugins>"

if [ $FOUND_CONFIG == "true" ]
then
   echo "$AUTHORIZATION_PLUGIN_CONFIG"
   sed -i -e "s/<\/broker>/$AUTHORIZATION_PLUGIN_CONFIG<\/broker>/g" /opt/app/apache-activemq/conf/activemq.xml
fi
exit 0


